# Site settings
title: Andrew James Tait
description: "Front-end/user interface developer based in Newcastle upon Tyne, England."
baseurl: ""
# url: "http://andrewjamestait.co.uk"

# Build settings
markdown: kramdown
permalink: pretty

exclude: [node_modules,Gruntfile.js,package.json,README.md]

kramdown:
  input: GFM
  use_coderay: true

  coderay:
    coderay_line_numbers: ''
